fix some issues and remove unnecessary stuff
UserOfficeProject/user-office-cron pull request #1
Opened 2020-10-30 11:07 UTC by martin-trajanovski

## Description

## Motivation and Context

## How Has This Been Tested

## Fixes

## Changes

## Tests included/Docs Updated?

- [x] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2020-11-02 09:59 UTC, peter-asztalos requested changes
Looks good, but it needs a build action also, so on merge we build and push the image

2020-11-02 10:24 UTC, peter-asztalos commented on .github/workflows/build-push.yml
> +          tags: dmsc/duo-cron-job
You forgot the tag :)

2020-11-02 10:32 UTC, peter-asztalos approved these changes

2020-11-03 09:13 UTC, jekabs-karklins approved these changes

2020-11-03 09:17 UTC, merged